languageCode = "zh-cn"
languageName = "简体中文"
title = "Xeonzilla's Note"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  dateFormat = "2006, 01-02"
  logo = "/image/logo.png"
  description = "\"用一个可以永远存活在互联网上的档案，记录我的琐碎灵感与思考\""

[params.author]
  name = "Xeonzilla"
  email = "xeonrao01@gmail.com"
  image = "image/author.png"
  bio = "\"XEON Endorses Open-sourcing Nvidia\""
  links = [
    { email = "mailto:xeonrao01@gmail.com" },
    { github = "https://github.com/xeonzilla" },
    { telegram = "https://t.me/xeonzilla" },
  ]
