languageCode = "zh-cn"
languageName = "简体中文"
title = "Xeonzilla's Note"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  dateFormat = "2006, 01-02"
  logo = "/img/logo.webp"
  description = "“用一个可以永远存活在互联网上的档案，记录我的琐碎灵感与思考”"

[params.author]
  name = "Xeonzilla"
  email = "xeonrao01@gmail.com"
  image = "/img/authors/Xeonzilla.webp"
  bio = "Yuri is life."
  links = [
    { email = "mailto:xeonrao01@gmail.com" },
    { github = "https://github.com/Xeonzilla/Xeonzilla.github.io" },
    { telegram = "https://t.me/xeonzilla" },
    { rss-square = "https://xeonzilla.github.io/index.xml"}
  ]
