[[main]]
  name = "主页"
  pageRef = "/"
  weight = 1

[[main]]
  name = "分类"
  weight = 2

[[main]]
  name = "标签"
  parent = "分类"
  pageRef = "tags"
  weight = 2

[[main]]
  name = "系列"
  parent = "分类"
  pageRef = "series"
  weight = 2

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 3

[[main]]
  name = "归档"
  pageRef = "posts"
  weight = 4

[[main]]
  identifier = "Travel"
  pre = "planet"
  title = "异次元之旅-跃迁"
  url = "https://travel.moe/go.html?travel=on"
  weight = "5"

[[main]]
  identifier = "Travelling"
  pre = "train-subway"
  title = "开往-友链接力"
  url = "https://www.travellings.cn/go.html"
  weight = "6"

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 1

[[footer]]
  name = "系列"
  pageRef = "series"
  weight = 2

[[footer]]
  name = "站点统计"
  title = "Umami"
  url = "https://xeonzilla-monitoring.netlify.app/share/2MfYEB3UVdTDRDLN/xeonzilla.github.io"
  weight = "3"