[[main]]
  name = "主页"
  pageRef = "/"
  weight = 1

[[main]]
  name = "分类"
  weight = 2

[[main]]
  name = "标签"
  parent = "分类"
  pageRef = "tags"
  weight = 2

[[main]]
  name = "系列"
  parent = "分类"
  pageRef = "series"
  weight = 2

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 3

[[main]]
  name = "归档"
  pageRef = "post"
  weight = 4

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 1

[[footer]]
  name = "系列"
  pageRef = "series"
  weight = 2
