defaultAppearance = "dark"
enableSearch = true
enableCodeCopy = true
mainSections = ["posts"]
disableImageOptimization = true
defaultBackgroundImage = "/img/defaultBackgroundImage.avif"
defaultFeaturedImage = "/img/defaultFeaturedImage.avif"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"

[header]
  layout = "fixed"
  
[footer]
  showAppearanceSwitcher = true

[homepage]
  layout = "background"
  homepageImage = "/img/defaultBackgroundImage.avif"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  layoutBackgroundBlur = true

[article]
  showDateUpdated = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  invertPagination = true
  showReadingTime = false
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = true
  showComments = true
  sharingLinks = [ "twitter", "reddit", "facebook", "email", "whatsapp", "telegram"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showTableOfContents = true
  showCards = true
  cardView = true
  constrainItemsWidth = true

[sitemap]
  excludedKinds = ["taxonomy"]

[taxonomy]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showTableOfContents = true
  cardView = true

[term]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showTableOfContents = true
  groupByYear = true
  cardView = true

[umamiAnalytics]
  websiteid = "6de88ea2-9a38-4253-b06c-c1b14db73769"
  domain = "xeonzilla-umami.netlify.app"

[verification]
  google = "ZMPkOyFD0j8QvFC2ZYLJqU9pZYMfda8VtXdYl-isr94"